// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID      string `json:"id"`
	UserID  string `json:"userId"`
	Content string `json:"content"`
	IsDone  bool   `json:"isDone"`
	User    *User  `json:"user"`
}

type User struct {
	ID              int    `json:"id"`
	Email           string `json:"email"`
	Name            string `json:"name"`
	ProfileImageURL string `json:"profileImageUrl"`
}
